name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies (client)
        working-directory: ./client
        run: npm ci

      - name: Run ESLint (client)
        working-directory: ./client
        run: npm run lint

      - name: Run tests (client)
        working-directory: ./client
        run: npm test -- --watchAll=false --coverage

      - name: Install dependencies (server)
        working-directory: ./server
        run: npm ci

      - name: Run ESLint (server)
        working-directory: ./server
        run: npm run lint

      - name: Run tests (server)
        working-directory: ./server
        run: npm test
